### PR TITLE
🐛 Fix wrong sales notification tip amount for quantity > 1 sale

### LINKED ISSUE #263: buy multiple copies misinterpreted as tipping
Screenshot 2025-01-13 at 16 27 07

this order is for buying 5 copies (5 x 0.99 = 4.95) instead of tipping 3.96

### PR DESCRIPTION
**Pull request by williamchong**
Fixes https://github.com/likecoin/nft-book-press/issues/263

### CODE REVIEW

File: src/util/ses.ts [hunk 1]
```diff
@@ -987,10 +988,11 @@ export function sendNFTBookSalesEmail({
   <br/>
   <p>Congratulation!</p>
   <p>${buyerEmail} has bought your book ${bookName} for $${amount}${isGift ? ` as a gift to ${giftToName}<${giftToEmail}>` : ''}.</p>`;
```
Comment (nwingt) [inline src/util/ses.ts:990]: should we also show quantity here?

Comment (williamchong) [reply src/util/ses.ts:990]: maybe we should just always show the `Price:` row

**Review by nwingt — APPROVED** [review]

**Review by AuroraHuang22 — APPROVED** [review]
